### PR TITLE
Add subsections to books

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
don't forget `make pre-commit`

**Comment by ironsidevsquincy** [comment]
:+1:

**Comment by guyvalerio** [comment]
How come we need the subdivision?

**Comment by matthew-andrews** [comment]
just playing around for weekend spike @guyvalerio

**Comment by matthew-andrews** [comment]
was going to put it live and then ask you for advice, honest :wink:

**Comment by guyvalerio** [comment]
:+1: 

http://goo.gl/Pnoyni

**Pull request merged**
